### ISSUE TITLE
Setting BottomBarPage Children to NavigationPage instances does not work

### ISSUE THREAD

**Issue by adrianknight89** [thrive-now/BottomNavigationBarXF#10]
In the sample app, instead of adding TabPage as child elements of BottomBarPage, add NavigationPage. Only the first tab gets set to a navigation page. The other tabs are broken.

**Comment by talhaa91** [comment]
Any update on this? We need to have a persistent tab bar even if we navigate to other pages by non-modal navigation

**Comment by andreinitescu** [comment]
Umm, why would you want to have NavigationPage inside a BottomBarPage (which is like XF's TabbedPage).
It doesn't seem like a good UX to me..
If instead of the BottomBarPage you had a TabbedPage could you add a Navigationpage inside it?

**Comment by talhaa91** [comment]
@adrianknight89 because that's the expected behavior. We want the bottom bar visible at all times. That's why we need to a Navigation page in each tab.

**Comment by JannieT** [comment]
When I add the children as follows I don't experience this:

```
var tabOne = new TabOnePage();
NavigationPage.SetHasNavigationBar(tabOne, false);
bottomBarPage.Children.Add(new NavigationPage(tabOne) { Title = "One", Icon = icon1 });

// same for tabTwo etc.
```

**Comment by japhiaolson** [comment]
For anyone still being held up by this bug, you can fix it by navigating to BottomBarPageRenderer.cs and in your `OnLayout `override the final line: `base.OnLayout(changed, l, t, r, b);` should be at top of that override function, not the bottom.

**Comment by sschmidt** [comment]
@japhiaolson great - thanks! Can you create a PR for that?

**Comment by zonkzen** [comment]
@sschmidt can you merge it and make a new nuget package?

**Comment by malokuS** [comment]
@sschmidt && @DominicFrei - Can you please update the nuget package with this, and recent fixes because this awesome library doesn't work on API 21 or above. Thanks in advance :)

**Comment by dave2ma** [comment]
Hello,  @sschmidt && @DominicFrei, 

is there a chance to merge this the next days? 

Best regards

**Comment by zonkzen** [comment]
@sschmidt && @DominicFrei,
Are you alive?
Please update the project with this issue and create new nuget version.

**Comment by angelru** [comment]
@zonkzen not working for me, of where download?

**Comment by zonkzen** [comment]
@sschmidt && @DominicFrei 
Can you merge this and create nuget?

**Comment by mawarnes** [comment]
pretty please?

**Comment by RaZp29** [comment]
would also be super happy if you updated the nuget @sschmidt

**Comment by sschmidt** [comment]
Sure! @japhiaolson would you mind creating a PR for that?
