### ISSUE TITLE
CurrentPageChanged event is not fired

### ISSUE THREAD

**Issue by Korayem** [thrive-now/BottomNavigationBarXF#12]
I can't simply do this inside BottomBar Page

```
this.CurrentPageChanged += async (object sender, EventArgs e) =>
			{
				if (!AppSettings.IsLogged)
				{
					await Navigation.PushAsync(new Welcome(), false);
					return;
				}
			};
```

**Comment by andreinitescu** [comment]
This method:

https://github.com/thrive-now/BottomNavigationBarXF/blob/master/BottomBar.Droid/Renderers/BottomBarPageRenderer.cs#L161

needs to call tell `Element` property (which is the XamarinForms BottomBar) to raise `CurrentPageChanged` event (BottomBar is derived from MultiPage), something like this:

`Element.RaiseCurrentPageChanged()` 

or something similar...

a PR would be welcome :)

**Comment by nbsoftware** [comment]
+1
Any news ?

**Comment by nbsoftware** [comment]
From what I understand, it seems that Xamarin Forms TabbedPage control lacks a virtual OnCurrentPageChanged method that can be overriden and called from the renderer.

**Comment by nbsoftware** [comment]
Ok I have a fix for this.
I'll do the PR tomorrow.

**Comment by nbsoftware** [comment]
There you go. PR #15.

**Comment by sschmidt** [comment]
PR merged
