### ISSUE TITLE
Attached Property TabColor not accessible through Xaml

### ISSUE THREAD

**Issue by escamoteur** [thrive-now/BottomNavigationBarXF#17]
Hi, 

I tried to set the TabColor from Xaml, but got the Runtime Error thet there is no Method SetTabBolor.

I have no idea why, perhaps you can add a sample Page in Xaml ?

Best
Thomas

**Comment by hadhoryth** [comment]
Hello, is there some news how to set tab color from xaml?

**Comment by lazmeister** [comment]
This should be resolved now https://github.com/thrive-now/BottomNavigationBarXF/pull/45
