### ISSUE TITLE
Problem with nuget 1.0.1

### ISSUE THREAD

**Issue by escamoteur** [thrive-now/BottomNavigationBarXF#19]
Hi,

I have no idea why, but when installing the package into my project it only instally the Droid Parte but not the platform independent part.
Maybe this because I'm using a shared project.

Will go back to the dlls.

Anybody experienced the same?

Cheers
Thomas

**Comment by DominicFrei** [comment]
@escamoteur Did you do a cross check? Other nuget version. Without a shared project, etc.
Would be nice to have some insights, in which case it works and in which it does not.

**Comment by escamoteur** [comment]
sorry, no time yet

**Comment by ice-j** [comment]
I can help with this. You need to manually reference the XamarinForms dll which can be found in the packages folder of your solution, then inside the BottomNavigationBarXF folder. If you can't find your way around this I'll make some tutorial for you with pictures. I'm using shared projects as well.

**Comment by escamoteur** [comment]
Ok that would be a solution. So you got the same problems?

**Comment by DominicFrei** [comment]
@ice-j Would you mind creating a PR so that we can share it with everyone else?

**Comment by ice-j** [comment]
@escamoteur Yes, I couldn't access the BottomBarPage class from the shared project without adding the forms reference manually.

@DominicFrei sure thing, will push tomorrow.

**Comment by DominicFrei** [comment]
Fixed by ice-j with PR #22 .

**Comment by Dids** [comment]
@DominicFrei I'm assuming the new nuget package will still need to be built and pushed to nuget.org?
