### ISSUE TITLE
Installing in Blank Xamarin Forms project

### ISSUE THREAD

**Issue by jbucka** [thrive-now/BottomNavigationBarXF#20]
Hi there,

I am attempting to install this package using the nuget package manager inside Visual Studio 2015.

However when I install I get the following error message:
`Could not install package 'ThriveGmbH.BottomNavigationBar.XF 1.0.1'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile111', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.`

Any help please?

**Comment by jbucka** [comment]
Done some more digging and it seems similar to issue 19. Basically I can install the package for the .Droid part of the solution but not for the main general part of the solution. Could someone please check that the nuget package is targeting the right PCL profile? Thanks.

**Comment by jbucka** [comment]
While this does not fix the issue, as a workaround I have been able to build the BottomNavigationBarXF solution myself and then manually included the references in my App solution.

**Comment by javiholcman** [comment]
The same issue here!

**Comment by DominicFrei** [comment]
Fixed by ice-j with PR #22 .
