### ISSUE TITLE
System.DividedByZeroException on Android if you have 0 Tabs

### ISSUE THREAD

**Issue by dave2ma** [thrive-now/BottomNavigationBarXF#24]
Only on Android you get a System.DividedByZeroException if you initialize a BottomNavigationBar without an Tab. This can happen, if you, for example, don't want to load any tab before login via a modal. Is This issue known?

**Comment by dave2ma** [comment]
Fixed That in void SetTabItems in AndroidRenderer:  
`void SetTabItems()
        {            
            BottomBarTab[] tabs = Element.Children.Select(page =>
            {
                var tabIconId = ResourceManagerEx.IdFromTitle(page.Icon, ResourceManager.DrawableClass);
                return new BottomBarTab(tabIconId, page.Title);
            }).ToArray();
            **if (tabs.Length == 0)**
                **return;**
            _bottomBar.SetItems(tabs);
        }`

**Comment by mawarnes** [comment]
Great fix, thanks for adding this code, until it is merged in it might be worth making sure people setup tabs. Sad to say this error caused me a days worth of spinning wheels, but really grateful for the plugin....it looks brilliant on Android
