### ISSUE TITLE
Navigation bar still displayed at the top

### ISSUE THREAD

**Issue by agouriou** [thrive-now/BottomNavigationBarXF#81]
Hi and thanks for this component.

I've added the reference to my Portable project. I can see the page, but the bar is still displayed at the top of the page.

There is no compilation error, but the behavior is the one of a standard TabbedPage.

Am I missing something?

```
<xf:BottomBarPage xmlns="http://xamarin.com/schemas/2014/forms"
         xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
         xmlns:local="clr-namespace:TestApp"
         xmlns:xf="clr-namespace:BottomBar.XamarinForms;assembly=BottomBar.XamarinForms"
         x:Class="TestApp.MainPageBottomTab">
<xf:BottomBarPage.Children>
    <local:Page1 />
    <local:Page2 />
    <local:Page3 />
</xf:BottomBarPage.Children>
```

Thanks

**Comment by agouriou** [comment]
I was missing the dependency "BottomNavigationBar" in my Nugget packages.

**Comment by mhdshbk** [comment]
@agouriou  Can you please provide the reference to your project, so that I can get a proper idea of implementing this component!
Thank you!

**Comment by agouriou** [comment]
My project is not open source. I've used the example here: https://github.com/thrive-now/BottomNavigationBarXF/tree/master/example-xaml/BottomBarXFExampleXaml

It's working as expected, just make sure to have the following nugget packages:
- BottomNavigationBar.XF (of course)
- BottomNavigationBar
- Newtonsoft.Json

And the following references (I'm using a PCL project):
PCL Project references:
- packages\ThriveGmbH.BottomNavigationBar.XF.1.0.2\lib\portable-net45+win8+wpa81\BottomBar.XamarinForms.dll

Android project references:
- packages\ThriveGmbH.BottomNavigationBar.XF.1.0.2\lib\MonoAndroid10\BottomBar.Droid.dll
- packages\BottomNavigationBar.1.4.0.3\lib\MonoAndroid403\BottomNavigationBar.dll

iOS project references:
- packages\ThriveGmbH.BottomNavigationBar.XF.1.0.2\lib\Xamarin.iOS10\BottomBar.XamarinForms.dll
