### ISSUE TITLE
CurrentPageChanged does not fire when current tab changes

### ISSUE THREAD

**Issue by adrianknight89** [thrive-now/BottomNavigationBarXF#9]
Please run the example app you've posted. CurrentPageChanged fires only at app startup. When the user changes the current tab, the event is not raised.

**Comment by andreinitescu** [comment]
see https://github.com/thrive-now/BottomNavigationBarXF/issues/12

**Comment by nbsoftware** [comment]
Fixed with PR #15 
Waiting to be merged, eventually.

**Comment by nbsoftware** [comment]
@sschmidt you can close this one too ;)
